podman_base_image: "opensuse/leap"
podman_base_image_tag: "15.3"
podman_fact_override:
  ansible_distribution: "openSUSE Leap"
  ansible_distribution_major_version: '15'
  ansible_distribution_version: '15.3'
  ansible_os_family: Suse
